CREATE ROLE IF NOT EXISTS LOADING;
CREATE ROLE IF NOT EXISTS TRANSFORM;
CREATE ROLE IF NOT EXISTS ANALYTICS;

-- Role grants
GRANT ROLE LOADING TO USER  HEALTH;
GRANT ROLE TRANSFORM TO USER  HEALTH;
GRANT ROLE ANALYTICS TO USER  HEALTH;

-- DATABASE PREVILEGES
GRANT ALL PRIVILEGES ON  DATABASE HEALTHCARE_RAW TO LOADING;
GRANT ALL PRIVILEGES ON DATABASE HEALTHCARE_RAW TO TRANSFORM;
GRANT ALL PRIVILEGES ON DATABASE HEALTHCARE_ANALYTICS TO TRANSFORM;
GRANT ALL PRIVILEGES ON DATABASE HEALTHCARE_ANALYTICS TO ANALYTICS;

CREATE SCHEMA IF NOT EXISTS HEALTHCARE_RAW.BRONZE;
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_RAW.SILVER;
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_RAW.SILVER_UTIL;

-- PREVILEGES WITH FUTURE GRANTS FOR SCHEMAS PRESENT IN HEALTHCARE_RAW
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE HEALTHCARE_RAW TO LOADING;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE HEALTHCARE_RAW TO LOADING;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE HEALTHCARE_RAW TO TRANSFORM;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE HEALTHCARE_RAW TO TRANSFORM;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE HEALTHCARE_RAW TO ANALYTICS;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE HEALTHCARE_RAW TO ANALYTICS;


-- PREVILEGES WITH FUTURE GRANTS FOR TABLES PRESENT IN SCHEMA HEALTHCARE_RAW
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA HEALTHCARE_RAW.BRONZE TO LOADING;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA HEALTHCARE_RAW.BRONZE TO TRANSFORM;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA HEALTHCARE_RAW.BRONZE TO ANALYTICS;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA HEALTHCARE_RAW.BRONZE TO LOADING;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA HEALTHCARE_RAW.BRONZE TO TRANSFORM;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA HEALTHCARE_RAW.BRONZE TO ANALYTICS;


GRANT ALL PRIVILEGES ON ALL STAGES IN SCHEMA HEALTHCARE_RAW.BRONZE TO LOADING;
GRANT ALL PRIVILEGES ON ALL STAGES IN SCHEMA HEALTHCARE_RAW.BRONZE TO TRANSFORM;
GRANT ALL PRIVILEGES ON ALL STAGES IN SCHEMA HEALTHCARE_RAW.BRONZE TO ANALYTICS;
GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA HEALTHCARE_RAW.BRONZE TO LOADING;
GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA HEALTHCARE_RAW.BRONZE TO TRANSFORM;
GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA HEALTHCARE_RAW.BRONZE TO ANALYTICS;

-- PREVILEGES WITH FUTURE GRANTS FOR TABLES PRESENT IN SCHEMA SYNTHEA_SILVER_UTIL
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA HEALTHCARE_RAW.SILVER_UTIL TO LOADING;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA HEALTHCARE_RAW.SILVER_UTIL TO TRANSFORM;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA HEALTHCARE_RAW.SILVER_UTIL TO ANALYTICS;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA HEALTHCARE_RAW.SILVER_UTIL TO LOADING;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA HEALTHCARE_RAW.SILVER_UTIL TO TRANSFORM;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA HEALTHCARE_RAW.SILVER_UTIL TO ANALYTICS;
