USE ROLE transform_role;

-- 3. CREATION OF DATABASES FOR SYNTHEA
CREATE DATABASE IF NOT EXISTS HCB;
CREATE DATABASE IF NOT EXISTS HEALTHCARE_ANALYTICS_NEW;
CREATE DATABASE IF NOT EXISTS "_RAW";


-- 4. CREATE SCHEMA IN THE DATABASES
CREATE OR REPLACE SCHEMA HCB.bronze;
CREATE OR REPLACE SCHEMA HEALTHCARE_ANALYTICS_NEW.SILVER;
CREATE OR REPLACE SCHEMA HEALTHCARE_ANALYTICS_NEW.GOLD;
CREATE OR REPLACE SCHEMA  "_RAW".PUBLIC;
