account_role: transform_role
wh: TRANSFORMING
db_csv: HCB
schema_csv: STAGING       # LOAD CSV data to this schema, then transform to bronze
db_json: HJB
schema_loading: LOADING       # MASTER_JSON etc.
schema_staging: STAGING       # clinical tables etc.
paths:
  shared_scripts: "D:\\Gitrepo\\synthea-healthcare-data-engineering\\sql_scripts\\shared_scripts"
  csv_scripts: "D:\\Gitrepo\\synthea-healthcare-data-engineering\\sql_scripts\\csv_scripts"
  json_scripts: "D:\\Gitrepo\\synthea-healthcare-data-engineering\\sql_scripts\\json_scripts"
  csv_dir: "D:\\dbt_projects\\healthcare_db\\csvs\\"
  csv_logs: "D:\\dbt_projects\\healthcare_db\\logs\\csv_logs"
  json_logs: "D:\\dbt_projects\\healthcare_db\\logs\\json_logs"
