CREATE OR REPLACE PROCEDURE MEDALLION_LAB.SILVER_UTIL.SP_APPLY_SCHEMA_CHANGES(p_batch_no STRING)
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  V_SQL STRING;
  C_NEW_TABLES CURSOR FOR
       WITH def as (
       SELECT DISTINCT L2.COLUMN_NAME, T.TABLE_NAME, L2.COLUMN_DATA_TYPE
    FROM MEDALLION_LAB.SILVER_UTIL.NEW_TABLES T
    JOIN MEDALLION_LAB.SILVER_UTIL.SYNTHEA_FLATTENED_L2 L2
      ON T.TABLE_NAME = L2.TABLE_NAME 
   )
   
    SELECT TABLE_NAME,
           LISTAGG('"' || COLUMN_NAME || '" ' || COLUMN_DATA_TYPE, ', ')
             WITHIN GROUP (ORDER BY COLUMN_NAME) AS COL_DEF
    FROM def  GROUP BY TABLE_NAME;

  C_NEW_COLS CURSOR FOR
    SELECT TABLE_NAME, COLUMN_NAME, COLUMN_DATA_TYPE
    FROM MEDALLION_LAB.SILVER_UTIL.NEW_COLUMNS;
BEGIN
  --------------------------------------------------------------------
  -- 1. BUILD TEMP METADATA TABLES
  --------------------------------------------------------------------
  CREATE OR REPLACE TEMP TABLE MEDALLION_LAB.SILVER_UTIL.NEW_TABLES AS
  WITH DIFF_RAW AS (
    SELECT DISTINCT TABLE_NAME
    FROM   MEDALLION_LAB.SILVER_UTIL.SYNTHEA_FLATTENED_L2
    WHERE batch_no =  :p_batch_no
    MINUS
    SELECT DISTINCT TABLE_NAME
    FROM   MEDALLION_LAB.SILVER_UTIL.SYNTHEA_FLATTENED_L2
    WHERE batch_no = CONCAT('Batch-',TO_NUMBER(replace(:p_batch_no,'Batch-','')-1))
  )
  SELECT TABLE_NAME FROM DIFF_RAW;

  CREATE OR REPLACE TEMP TABLE MEDALLION_LAB.SILVER_UTIL.NEW_COLUMNS AS
  WITH DIFF_RAW AS (
    SELECT DISTINCT COLUMN_NAME, COLUMN_DATA_TYPE, TABLE_NAME
    FROM   MEDALLION_LAB.SILVER_UTIL.SYNTHEA_FLATTENED_L2
    MINUS
    SELECT DISTINCT COLUMN_NAME, COLUMN_DATA_TYPE, TABLE_NAME
    FROM   MEDALLION_LAB.SILVER_UTIL.SYNTHEA_FLATTENED_L2
    WHERE batch_no = CONCAT('Batch-',TO_NUMBER(replace(:p_batch_no,'Batch-','')-1))
  )
  SELECT *
  FROM DIFF_RAW
  WHERE TABLE_NAME NOT IN (SELECT TABLE_NAME FROM MEDALLION_LAB.SILVER_UTIL.NEW_TABLES);

  --------------------------------------------------------------------
  -- 2. LOOP #1: CREATE NEW SILVER TABLES
  --------------------------------------------------------------------
  FOR REC IN C_NEW_TABLES DO
    V_SQL := 'CREATE OR REPLACE TABLE MEDALLION_LAB.SILVER."' || REC.TABLE_NAME || '" (' ||
             'PATIENT_ID VARCHAR(16777216), LOAD_TS TIMESTAMP, batch_no VARCHAR(16777216), ' || REC.COL_DEF || ');';

    EXECUTE IMMEDIATE V_SQL;
  END FOR;

  --------------------------------------------------------------------
  -- 3. LOOP #2: ADD NEW COLUMNS TO EXISTING SILVER TABLES
  --------------------------------------------------------------------
  FOR REC2 IN C_NEW_COLS DO
    V_SQL := 'ALTER TABLE MEDALLION_LAB.SILVER."' || REC2.TABLE_NAME || '"' ||
             ' ADD COLUMN IF NOT EXISTS "' || REC2.COLUMN_NAME || '" ' ||
             REC2.COLUMN_DATA_TYPE || ';';

    EXECUTE IMMEDIATE V_SQL;
  END FOR;

  DROP TABLE IF EXISTS MEDALLION_LAB.SILVER_UTIL.NEW_TABLES;
  DROP TABLE IF EXISTS MEDALLION_LAB.SILVER_UTIL.NEW_COLUMNS;

  RETURN 'OK';
END;
$$;
