CREATE OR REPLACE PROCEDURE MEDALLION_LAB.SILVER_UTIL.SP_LOAD_SILVER_DATA(p_batch_no STRING)
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  V_SQL STRING;
  
  C_INS CURSOR FOR
    SELECT 
      TABLE_NAME,
      'INSERT INTO MEDALLION_LAB.SILVER."' || TABLE_NAME || '"(
  "PATIENT_ID",
  "LOAD_TS",
  "BATCH_NO",
  ' ||
      RTRIM(
        LISTAGG('"' || COLUMN_NAME || '"', ',\n'), 
        ',\n'
      ) || '
)
SELECT DISTINCT 
  L.PATIENT_ID AS "PATIENT_ID",
  CURRENT_TIMESTAMP() AS "LOAD_TS", 
  L.batch_no,
  ' ||
      RTRIM(
        LISTAGG('O.VALUE:"' || COLUMN_NAME || '" AS "' || COLUMN_NAME || '"', ',\n'), 
        ',\n'
      ) || '
FROM MEDALLION_LAB.SILVER_UTIL.TMP_SYNTHEA_FLATTENED_L1 L,
     LATERAL FLATTEN(INPUT => L.CLINICAL_JSON:' || TABLE_NAME || ') O
WHERE ARRAY_CONTAINS(''' || TABLE_NAME || '''::VARIANT, L.PAT_TABLES);'
        AS INSERT_CONSTRUCT
    FROM MEDALLION_LAB.SILVER_UTIL.TMP_SYNTHEA_FLATTENED_L2
    GROUP BY TABLE_NAME;
    
BEGIN
  -- Create filtered temp tables BEFORE cursor opens (static names)
  EXECUTE IMMEDIATE 'CREATE OR REPLACE TEMP TABLE MEDALLION_LAB.SILVER_UTIL.TMP_SYNTHEA_FLATTENED_L1 
                     AS SELECT * FROM MEDALLION_LAB.BRONZE.SYNTHEA_FLATTENED_L1 WHERE BATCH_NO = ''' || :p_batch_no || '''';
                     
  EXECUTE IMMEDIATE 'CREATE OR REPLACE TEMP TABLE MEDALLION_LAB.SILVER_UTIL.TMP_SYNTHEA_FLATTENED_L2 
                     AS SELECT * FROM MEDALLION_LAB.SILVER_UTIL.SYNTHEA_FLATTENED_L2 WHERE BATCH_NO = ''' || :p_batch_no || '''';

  FOR REC IN C_INS DO
    V_SQL := REC.INSERT_CONSTRUCT;
    EXECUTE IMMEDIATE V_SQL;
  END FOR;

  RETURN 'SUCCESS - Loaded batch: ' || :p_batch_no;
END;
$$;