
SHOW TASKS IN MEDALLION_LAB.SILVER_UTIL;



ALTER TASK MEDALLION_LAB.SILVER_UTIL.MASTER_TO_L1_MERGE SUSPEND;
ALTER TASK MEDALLION_LAB.SILVER_UTIL.L1_TO_L2_MERGE SUSPEND;  
ALTER TASK MEDALLION_LAB.SILVER_UTIL.SP_APPLY_SCHEMA_CHANGES SUSPEND; 
ALTER TASK MEDALLION_LAB.SILVER_UTIL.SP_LOAD_SILVER_DATA SUSPEND;
ALTER TASK MEDALLION_LAB.SILVER_UTIL.SP_PIPELINE_AUDIT SUSPEND;

ALTER TASK MEDALLION_LAB.SILVER_UTIL.MASTER_TO_L1_MERGE 
  SET SCHEDULE = 'USING CRON 0 0 1 * * Asia/Kolkata';  -- 1st day, 12AM IST every month


 
ALTER TASK MEDALLION_LAB.SILVER_UTIL.SP_PIPELINE_AUDIT RESUME;
ALTER TASK MEDALLION_LAB.SILVER_UTIL.SP_LOAD_SILVER_DATA RESUME;
ALTER TASK MEDALLION_LAB.SILVER_UTIL.SP_APPLY_SCHEMA_CHANGES RESUME; 
ALTER TASK MEDALLION_LAB.SILVER_UTIL.L1_TO_L2_MERGE RESUME; 
ALTER TASK MEDALLION_LAB.SILVER_UTIL.MASTER_TO_L1_MERGE RESUME;

EXECUTE TASK MEDALLION_LAB.SILVER_UTIL.MASTER_TO_L1_MERGE;


select * from 
(SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(RESULT_LIMIT => 100)) 
ORDER BY SCHEDULED_TIME DESC) where database_name  = 'MEDALLION_LAB';
