WITH silver_data as (
select 
"START" AS PROCEDURE_START
, "STOP" AS PROCEDURE_STOP
, "PATIENT" AS PATIENT_ID
, "ENCOUNTER" AS ENCOUNTER_ID
, "CODE" AS PROCEDURE_CODE
, "DESCRIPTION" AS PROCEDURE_DESCRIPTION
, "BASE_COST" AS PROCEDURE_BASE_COST
, "REASONCODE" AS PROCEDURE_REASONCODE
, "REASONDESCRIPTION" AS PROCEDURE_REASONDESCRIPTION
from {{ ref('csv_bronze__procedures') }} as proc
)

select * from silver_data

