CREATE WAREHOUSE IF NOT EXISTS TRANSFORMING WITH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

  
-- Roles
CREATE ROLE transform_role;

GRANT USAGE ON WAREHOUSE TRANSFORMING TO ROLE transform_role;
  

-- Users (Your specs)
CREATE USER HEALTHCARE PASSWORD = 'Healthcare_User123' 
  DEFAULT_ROLE = transform_role DEFAULT_WAREHOUSE = TRANSFORMING 
  MUST_CHANGE_PASSWORD = FALSE COMMENT = 'Healthcare Dev';

CREATE USER HEALTH PASSWORD = 'Healthcare_User123' 
  DEFAULT_ROLE = transform_role DEFAULT_WAREHOUSE = TRANSFORMING 
  MUST_CHANGE_PASSWORD = FALSE COMMENT = 'Healthcare Dev';

-- Grants (Your code)
GRANT ROLE transform_role TO USER HEALTH;
GRANT ROLE transform_role TO USER HEALTHCARE;
GRANT ROLE transform_role TO USER THERAMCHU;

-- Core Privs (transform_role creates everything from here)
GRANT CREATE DATABASE, CREATE WAREHOUSE ON ACCOUNT TO ROLE transform_role;

GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE transform_role;

GRANT EXECUTE TASK ON ACCOUNT TO ROLE transform_role;