-------------------------------------------------------------------------------
-- 1) CREATE DATABASES
-------------------------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS SYNTHEA_RAW;
CREATE DATABASE IF NOT EXISTS SYNTHEA_ANALYTICS;

-------------------------------------------------------------------------------
-- 2) CREATE SCHEMAS
-------------------------------------------------------------------------------
-- RAW Layer
CREATE SCHEMA IF NOT EXISTS SYNTHEA_RAW.RAW_DATA;
CREATE SCHEMA IF NOT EXISTS SYNTHEA_RAW.EXTERNAL_STAGES;
CREATE SCHEMA IF NOT EXISTS SYNTHEA_RAW.UTIL;

-- Analytics Layer
CREATE SCHEMA IF NOT EXISTS SYNTHEA_ANALYTICS.DEV;
CREATE SCHEMA IF NOT EXISTS SYNTHEA_ANALYTICS.ANALYTICS;

-------------------------------------------------------------------------------
-- 3) CREATE USER
-------------------------------------------------------------------------------
CREATE USER IF NOT EXISTS HEALTHCARE
  PASSWORD = 'Healthcare_User123'
  DEFAULT_ROLE = TRANSFORM
  DEFAULT_WAREHOUSE = TRANSFORMING
  MUST_CHANGE_PASSWORD = FALSE;

-------------------------------------------------------------------------------
-- 4) ROLES (best practice)
-------------------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS LOADING;
CREATE ROLE IF NOT EXISTS TRANSFORM;
CREATE ROLE IF NOT EXISTS ANALYTICS;
GRANT ROLE LOADING TO USER THERAMCHU;

-- Role grants
GRANT USAGE ON DATABASE SYNTHEA_RAW TO LOADING;
GRANT ALL ON DATABASE SYNTHEA_RAW TO LOADING;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SYNTHEA_RAW TO LOADING;
GRANT ALL PRIVILEGES ON SCHEMA SYNTHEA_RAW.RAW_DATA TO LOADING;
GRANT ALL PRIVILEGES ON SCHEMA SYNTHEA_RAW.EXTERNAL_STAGES TO LOADING;

GRANT ALL PRIVILEGES  ON DATABASE SYNTHEA_ANALYTICS TO TRANSFORM;
GRANT ALL PRIVILEGES  ON DATABASE SYNTHEA_RAW TO TRANSFORM;

GRANT ALL PRIVILEGES  ON SCHEMA SYNTHEA_RAW.UTIL TO ROLE TRANSFORM;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SYNTHEA_ANALYTICS TO TRANSFORM;
GRANT ALL PRIVILEGES ON SCHEMA SYNTHEA_ANALYTICS.DEV TO TRANSFORM;

GRANT USAGE ON DATABASE SYNTHEA_ANALYTICS TO ANALYTICS;
GRANT USAGE ON SCHEMA SYNTHEA_ANALYTICS.ANALYTICS TO ANALYTICS;
GRANT SELECT ON ALL TABLES IN SCHEMA SYNTHEA_ANALYTICS.ANALYTICS TO ANALYTICS;

-- Assign roles to user
GRANT ROLE LOADING TO USER HEALTHCARE;
GRANT ROLE TRANSFORM TO USER HEALTHCARE;
GRANT ROLE ANALYTICS TO USER HEALTHCARE;

