CREATE OR REPLACE TABLE SYNTHEA_RAW.RAW_DATA.master_json
(
    raw VARIANT,
    filename STRING,
    load_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


COPY INTO SYNTHEA_RAW.RAW_DATA.master_json (raw, filename) FROM (SELECT $1, METADATA$FILENAME FROM @SYNTHEA_RAW.EXTERNAL_STAGES.stage_synthea_batch_02) FILE_FORMAT = (TYPE = JSON) ON_ERROR = 'CONTINUE';
COPY INTO SYNTHEA_RAW.RAW_DATA.master_json (raw, filename) FROM (SELECT $1, METADATA$FILENAME FROM @SYNTHEA_RAW.EXTERNAL_STAGES.stage_synthea_batch_03) FILE_FORMAT = (TYPE = JSON) ON_ERROR = 'CONTINUE';
COPY INTO SYNTHEA_RAW.RAW_DATA.master_json (raw, filename) FROM (SELECT $1, METADATA$FILENAME FROM @SYNTHEA_RAW.EXTERNAL_STAGES.stage_synthea_batch_04) FILE_FORMAT = (TYPE = JSON) ON_ERROR = 'CONTINUE';
COPY INTO SYNTHEA_RAW.RAW_DATA.master_json (raw, filename) FROM (SELECT $1, METADATA$FILENAME FROM @SYNTHEA_RAW.EXTERNAL_STAGES.stage_synthea_batch_05) FILE_FORMAT = (TYPE = JSON) ON_ERROR = 'CONTINUE';
COPY INTO SYNTHEA_RAW.RAW_DATA.master_json (raw, filename) FROM (SELECT $1, METADATA$FILENAME FROM @SYNTHEA_RAW.EXTERNAL_STAGES.stage_synthea_batch_06) FILE_FORMAT = (TYPE = JSON) ON_ERROR = 'CONTINUE';
COPY INTO SYNTHEA_RAW.RAW_DATA.master_json (raw, filename) FROM (SELECT $1, METADATA$FILENAME FROM @SYNTHEA_RAW.EXTERNAL_STAGES.stage_synthea_batch_07) FILE_FORMAT = (TYPE = JSON) ON_ERROR = 'CONTINUE';
COPY INTO SYNTHEA_RAW.RAW_DATA.master_json (raw, filename) FROM (SELECT $1, METADATA$FILENAME FROM @SYNTHEA_RAW.EXTERNAL_STAGES.stage_synthea_batch_08) FILE_FORMAT = (TYPE = JSON) ON_ERROR = 'CONTINUE';
COPY INTO SYNTHEA_RAW.RAW_DATA.master_json (raw, filename) FROM (SELECT $1, METADATA$FILENAME FROM @SYNTHEA_RAW.EXTERNAL_STAGES.stage_synthea_batch_09) FILE_FORMAT = (TYPE = JSON) ON_ERROR = 'CONTINUE';
COPY INTO SYNTHEA_RAW.RAW_DATA.master_json (raw, filename) FROM (SELECT $1, METADATA$FILENAME FROM @SYNTHEA_RAW.EXTERNAL_STAGES.stage_synthea_batch_10) FILE_FORMAT = (TYPE = JSON) ON_ERROR = 'CONTINUE';

COPY INTO SYNTHEA_RAW.RAW_DATA.master_json (raw, filename) FROM (SELECT $1, METADATA$FILENAME FROM @SYNTHEA_RAW.EXTERNAL_STAGES.stage_synthea_STREAM_100_PATS) FILE_FORMAT = (TYPE = JSON) ON_ERROR = 'CONTINUE';
