CREATE OR REPLACE STREAM synthea_raw.util.patient_data_ddl_str
  ON TABLE synthea_raw.raw_data.master_json;

ALTER TASK synthea_raw.util.task_synthea_flattened_L1 SUSPEND;
ALTER TASK synthea_raw.util.task_synthea_flattened_L2 SUSPEND;

  
CREATE OR REPLACE  TASK synthea_raw.util.task_synthea_table_ddl
  WAREHOUSE = TRANSFORMING
  AFTER synthea_raw.util.task_synthea_flattened_L2
AS
BEGIN
TRUNCATE TABLE SYNTHEA_RAW.RAW_DATA."ALLERGYINTOLERANCE";
TRUNCATE TABLE SYNTHEA_RAW.RAW_DATA."CAREPLAN";
TRUNCATE TABLE SYNTHEA_RAW.RAW_DATA."CLAIM";
TRUNCATE TABLE SYNTHEA_RAW.RAW_DATA."CONDITION";
TRUNCATE TABLE SYNTHEA_RAW.RAW_DATA."DIAGNOSTICREPORT";
TRUNCATE TABLE SYNTHEA_RAW.RAW_DATA."ENCOUNTER";
TRUNCATE TABLE SYNTHEA_RAW.RAW_DATA."EXPLANATIONOFBENEFIT";
TRUNCATE TABLE SYNTHEA_RAW.RAW_DATA."GOAL";
TRUNCATE TABLE SYNTHEA_RAW.RAW_DATA."IMAGINGSTUDY";
TRUNCATE TABLE SYNTHEA_RAW.RAW_DATA."IMMUNIZATION";
TRUNCATE TABLE SYNTHEA_RAW.RAW_DATA."MEDICATIONREQUEST";
TRUNCATE TABLE SYNTHEA_RAW.RAW_DATA."OBSERVATION";
TRUNCATE TABLE SYNTHEA_RAW.RAW_DATA."ORGANIZATION";
TRUNCATE TABLE SYNTHEA_RAW.RAW_DATA."PATIENT";
TRUNCATE TABLE SYNTHEA_RAW.RAW_DATA."PRACTITIONER";
TRUNCATE TABLE SYNTHEA_RAW.RAW_DATA."PROCEDURE";

END;

ALTER TASK synthea_raw.util.task_synthea_table_ddl RESUME;
ALTER TASK synthea_raw.util.task_synthea_flattened_L2 RESUME;
ALTER TASK synthea_raw.util.task_synthea_flattened_L1 RESUME;
