USE ROLE transform_role;
USE WAREHOUSE TRANSFORMING;

-- 3. CREATION OF DATABASES FOR SYNTHEA
CREATE DATABASE IF NOT EXISTS HEALTHCARE_JSON_RAW;
CREATE DATABASE IF NOT EXISTS HEALTHCARE_ANALYTICS_NEW;


-- 4. CREATE SCHEMA IN THE DATABASES
CREATE SCHEMA HEALTHCARE_JSON_RAW.STAGING;
CREATE SCHEMA HEALTHCARE_JSON_RAW.BRONZE;
