USE ROLE transform_role;
USE WAREHOUSE TRANSFORMING;
USE DATABASE HEALTHCARE_JSON_RAW;
USE SCHEMA HEALTHCARE_JSON_RAW.STAGING;


CREATE TASK MASTER_TO_L1_MERGE 
    AS  CALL MASTER_TO_L1_MERGE(select max(batch_no)  from MASTER_JSON);
CREATE TASK L1_TO_L2_MERGE AFTER MASTER_TO_L1_MERGE 
    AS CALL L1_TO_L2_MERGE(select max(batch_no)  from MASTER_JSON);
CREATE TASK SP_APPLY_SCHEMA_CHANGES AFTER L1_TO_L2_MERGE 
    AS CALL SP_APPLY_SCHEMA_CHANGES(select max(batch_no)  from MASTER_JSON);
CREATE TASK  SP_LOAD_SILVER_DATA AFTER SP_APPLY_SCHEMA_CHANGES
    AS CALL SP_LOAD_SILVER_DATA(select max(batch_no)  from MASTER_JSON);
CREATE TASK SP_PIPELINE_AUDIT AFTER SP_LOAD_SILVER_DATA
    AS CALL SP_PIPELINE_AUDIT(select max(batch_no)  from MASTER_JSON);

ALTER TASK MASTER_TO_L1_MERGE SUSPEND;
ALTER TASK L1_TO_L2_MERGE SUSPEND;  
ALTER TASK SP_APPLY_SCHEMA_CHANGES SUSPEND; 
ALTER TASK SP_LOAD_SILVER_DATA SUSPEND;
ALTER TASK SP_PIPELINE_AUDIT SUSPEND;


show tables in HEALTHCARE_JSON_RAW.STAGING;

ALTER TASK MASTER_TO_L1_MERGE 
  SET SCHEDULE = 'USING CRON 0 0 1 * * Asia/Kolkata';  -- 1st day, 12AM IST every month


 
ALTER TASK SP_PIPELINE_AUDIT RESUME;
ALTER TASK SP_LOAD_SILVER_DATA RESUME;
ALTER TASK SP_APPLY_SCHEMA_CHANGES RESUME; 
ALTER TASK L1_TO_L2_MERGE RESUME; 
ALTER TASK MASTER_TO_L1_MERGE RESUME;

SHOW TASKS IN HEALTHCARE_JSON_RAW.STAGING;

select top 10 * from master_json;


select count(*), count(distinct patient_id) from synthea_flattened_l1;