CREATE OR REPLACE PROCEDURE MEDALLION_LAB.SILVER_UTIL.MASTER_TO_L1_MERGE(p_batch_no STRING)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  -- 1. TEMP FLATTENED_JSON FROM MASTER_JSON STREAM (batch data only)
  CREATE OR REPLACE TEMP TABLE MEDALLION_LAB.BRONZE.COL_DATA_FOR_AGG AS  
    SELECT  
      raw:entry[0].fullUrl::string AS patient_id,
      batch_no,
      f.value:resource:resourceType AS fkey,
      f.value:resource AS fval,
      g.key AS column_name,
      typeof(g.value) AS data_type_L1
    FROM MEDALLION_LAB.BRONZE.MASTER_JSON
    , LATERAL FLATTEN(INPUT => raw:entry) F
    , LATERAL FLATTEN(INPUT => FVAL) G
    WHERE batch_no =  :p_batch_no ; -- Get data for only the param batch defined
  
  -- 2. ARRAY_AGG for L1 clinical JSON
  CREATE OR REPLACE TEMP TABLE MEDALLION_LAB.BRONZE.ARRAY_AGG_FLATTENED_JSON AS
    SELECT 
      PATIENT_ID, FKEY,
      CAST(ARRAY_AGG(FVAL) AS VARIANT) AS FVAL 
    FROM MEDALLION_LAB.BRONZE.COL_DATA_FOR_AGG  
    GROUP BY 1,2; 

  -- 3. COL_META for L1 schema metadata
  CREATE OR REPLACE TEMP TABLE MEDALLION_LAB.BRONZE.COL_META_JSON AS
    SELECT PATIENT_ID, max(batch_no) as batch_no,
      ARRAY_AGG(OBJECT_CONSTRUCT(
        'TABLE', FKEY, 'COLUMN', COLUMN_NAME, 'DATATYPE', DATA_TYPE_L1
      ))::VARIANT AS COL_VAL
    FROM (
      SELECT DISTINCT PATIENT_ID, FKEY, COLUMN_NAME, DATA_TYPE_L1,batch_no
      FROM MEDALLION_LAB.BRONZE.COL_DATA_FOR_AGG WHERE batch_no =  :p_batch_no 
    ) D
    GROUP BY PATIENT_ID;
    
  -- 4. L1 MERGE SOURCE (your temp approach - perfect for MERGE)
  CREATE OR REPLACE TEMP TABLE MEDALLION_LAB.BRONZE.TEMP_SYNTHEA_FLATTENED_L1 AS
  SELECT
      A.PATIENT_ID,
      :p_batch_no  as batch_no,
      CURRENT_TIMESTAMP AS LOAD_TS,
      ARRAY_AGG(A.FKEY) AS PAT_TABLES,
      MAX(C.COL_VAL) AS COL_META,
      OBJECT_AGG(A.FKEY, A.FVAL) AS CLINICAL_JSON
  FROM MEDALLION_LAB.BRONZE.ARRAY_AGG_FLATTENED_JSON A
  JOIN MEDALLION_LAB.BRONZE.COL_META_JSON C
    ON A.PATIENT_ID = C.PATIENT_ID
  WHERE C.batch_no =  :p_batch_no 
  GROUP BY A.PATIENT_ID;

    INSERT INTO MEDALLION_LAB.BRONZE.SYNTHEA_FLATTENED_L1 (PATIENT_ID, LOAD_TS, PAT_TABLES, COL_META, CLINICAL_JSON,batch_no)
    SELECT source.PATIENT_ID, source.LOAD_TS, source.PAT_TABLES, source.COL_META, source.CLINICAL_JSON,:p_batch_no  FROM MEDALLION_LAB.BRONZE.TEMP_SYNTHEA_FLATTENED_L1 source;

END;
$$;