CREATE OR REPLACE PROCEDURE MEDALLION_LAB.SILVER_UTIL.L1_TO_L2_MERGE (p_batch_no STRING)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN

CREATE OR REPLACE TEMP TABLE MEDALLION_LAB.BRONZE.TEMP_SYNTHEA_FLATTENED_L2 AS
SELECT
    TABLE_NAME       AS TABLE_NAME,
    COLUMN_NAME      AS COLUMN_NAME,
    COL_DATA_TYPE    AS COLUMN_DATA_TYPE,
    batch_no
FROM (
    SELECT
        F.VALUE:COLUMN::STRING   AS COLUMN_NAME,
        F.VALUE:TABLE::STRING    AS TABLE_NAME,
        F.VALUE:DATATYPE::STRING AS COL_DATA_TYPE,
        :p_batch_no as batch_no
    FROM MEDALLION_LAB.BRONZE.SYNTHEA_FLATTENED_L1,
         LATERAL FLATTEN (INPUT => COL_META) F
    WHERE batch_no =  :p_batch_no 
    GROUP BY 1,2,3,4
    ORDER BY 1,2,3,4
) S;

MERGE INTO MEDALLION_LAB.SILVER_UTIL.SYNTHEA_FLATTENED_L2 AS target
  USING MEDALLION_LAB.BRONZE.TEMP_SYNTHEA_FLATTENED_L2 AS source
  ON target.TABLE_NAME = source.TABLE_NAME AND target.COLUMN_NAME = source.COLUMN_NAME AND target.batch_no  = source.batch_no
  WHEN MATCHED THEN
    UPDATE SET 
      TABLE_NAME = source.TABLE_NAME,
      COLUMN_NAME = source.COLUMN_NAME,
      COLUMN_DATA_TYPE = source.COLUMN_DATA_TYPE, 
      batch_no     = source.batch_no
  WHEN NOT MATCHED THEN
    INSERT (TABLE_NAME,COLUMN_NAME,COLUMN_DATA_TYPE,batch_no)
    VALUES (source.TABLE_NAME,source.COLUMN_NAME,source.COLUMN_DATA_TYPE,source.batch_no);
END;
$$;