CREATE TASK MEDALLION_LAB.SILVER_UTIL.MASTER_TO_L1_MERGE 
    AS  CALL MEDALLION_LAB.SILVER_UTIL.MASTER_TO_L1_MERGE(select max(batch_no)  from MEDALLION_LAB.BRONZE.MASTER_JSON);
CREATE TASK MEDALLION_LAB.SILVER_UTIL.L1_TO_L2_MERGE AFTER MEDALLION_LAB.SILVER_UTIL.MASTER_TO_L1_MERGE 
    AS CALL MEDALLION_LAB.SILVER_UTIL.L1_TO_L2_MERGE(select max(batch_no)  from MEDALLION_LAB.BRONZE.MASTER_JSON);
CREATE TASK MEDALLION_LAB.SILVER_UTIL.SP_APPLY_SCHEMA_CHANGES AFTER MEDALLION_LAB.SILVER_UTIL.L1_TO_L2_MERGE 
    AS CALL MEDALLION_LAB.SILVER_UTIL.SP_APPLY_SCHEMA_CHANGES(select max(batch_no)  from MEDALLION_LAB.BRONZE.MASTER_JSON);
CREATE TASK  MEDALLION_LAB.SILVER_UTIL.SP_LOAD_SILVER_DATA AFTER MEDALLION_LAB.SILVER_UTIL.SP_APPLY_SCHEMA_CHANGES
    AS CALL MEDALLION_LAB.SILVER_UTIL.SP_LOAD_SILVER_DATA(select max(batch_no)  from MEDALLION_LAB.BRONZE.MASTER_JSON);
CREATE TASK MEDALLION_LAB.SILVER_UTIL.SP_PIPELINE_AUDIT AFTER MEDALLION_LAB.SILVER_UTIL.SP_LOAD_SILVER_DATA
    AS CALL MEDALLION_LAB.SILVER_UTIL.SP_PIPELINE_AUDIT(select max(batch_no)  from MEDALLION_LAB.BRONZE.MASTER_JSON);

