sources:
  - name: clinical_data
    tables:
      - name: encounters
      - name: immunizations
      - name: medications
      - name: observations
      - name: procedures
      - name: json_encounters
      - name: json_immunizations
      - name: json_medications
      - name: json_observations
      - name: json_procedures
  - name: synthea
    database: HEALTHCARE_RAW
    schema: DBT_BRONZE
    tables:
      - name: master_json
  - name: raw_data
    database: healthcare_raw
    tables:
      - name: allergies
      - name: careplans
      - name: claims
      - name: claims_transactions
      - name: conditions
      - name: devices
      - name: encounters
      - name: imaging_studies
      - name: immunizations
      - name: medications
      - name: observations
      - name: organizations
      - name: patients
      - name: payer_transitions
      - name: payers
      - name: procedures
      - name: providers
      - name: supplies
      - name: table_column_preview