-- 1. CREATION OF ROLES
CREATE OR REPLACE  ROLE loading_role;
CREATE OR REPLACE ROLE transform_role;


-- 2. GRANT ROLES TO USERS 
GRANT ROLE loading_role TO USER  HEALTH;
GRANT ROLE transform_role TO USER  HEALTH;
GRANT ROLE loading_role TO USER  HEALTHCARE;
GRANT ROLE transform_role TO USER  HEALTHCARE;
GRANT ROLE loading_role TO USER  THERAMCHU;
GRANT ROLE transform_role TO USER  THERAMCHU;


DROP DATABASE IF EXISTS HEALTHCARE_CSV_RAW CASCADE;
DROP DATABASE IF EXISTS HEALTHCARE_ANALYTICS_NEW CASCADE;
DROP DATABASE IF EXISTS "_RAW" CASCADE;

-- 3. CREATION OF DATABASES FOR SYNTHEA
CREATE DATABASE IF NOT EXISTS HEALTHCARE_CSV_RAW;
CREATE DATABASE IF NOT EXISTS HEALTHCARE_ANALYTICS_NEW;
CREATE DATABASE IF NOT EXISTS "_RAW";


-- 4. CREATE SCHEMA IN THE DATABASES
CREATE SCHEMA HEALTHCARE_CSV_RAW.bronze;
CREATE SCHEMA HEALTHCARE_ANALYTICS_NEW.SILVER;
CREATE SCHEMA HEALTHCARE_ANALYTICS_NEW.GOLD;
CREATE SCHEMA IF NOT EXISTS "_RAW".PUBLIC;


-- 5. RBAC
GRANT ALL PRIVILEGES ON DATABASE "_RAW" TO ROLE transform_role;
GRANT ALL PRIVILEGES ON DATABASE "_RAW" TO ROLE loading_role;
GRANT ALL PRIVILEGES ON DATABASE HEALTHCARE_CSV_RAW TO ROLE loading_role;
GRANT ALL PRIVILEGES ON DATABASE HEALTHCARE_CSV_RAW TO ROLE transform_role;  -- All RAW
GRANT ALL PRIVILEGES ON DATABASE HEALTHCARE_ANALYTICS_NEW TO ROLE transform_role;

GRANT ALL PRIVILEGES ON SCHEMA HEALTHCARE_CSV_RAW.bronze TO ROLE loading_role;
GRANT ALL PRIVILEGES ON SCHEMA HEALTHCARE_CSV_RAW.bronze TO ROLE transform_role;
GRANT ALL PRIVILEGES ON SCHEMA HEALTHCARE_CSV_RAW.bronze TO ROLE transform_role;
GRANT ALL PRIVILEGES ON SCHEMA HEALTHCARE_ANALYTICS_NEW.SILVER TO ROLE transform_role;
GRANT ALL PRIVILEGES ON SCHEMA HEALTHCARE_ANALYTICS_NEW.gold TO ROLE transform_role;


GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA HEALTHCARE_CSV_RAW.bronze TO ROLE loading_role;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA HEALTHCARE_CSV_RAW.bronze TO ROLE transform_role;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA HEALTHCARE_ANALYTICS_NEW.gold TO ROLE transform_role;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA HEALTHCARE_ANALYTICS_NEW.SILVER TO ROLE transform_role;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA HEALTHCARE_CSV_RAW.bronze TO ROLE loading_role;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA HEALTHCARE_CSV_RAW.bronze TO ROLE transform_role;

GRANT CREATE TABLE ON SCHEMA HEALTHCARE_CSV_RAW.BRONZE TO ROLE transform_role;
GRANT CREATE TABLE ON SCHEMA  HEALTHCARE_ANALYTICS_NEW.SILVER TO ROLE transform_role;
GRANT CREATE TABLE ON SCHEMA  HEALTHCARE_ANALYTICS_NEW.GOLD TO ROLE transform_role;

GRANT CREATE STAGE, USAGE ON SCHEMA HEALTHCARE_CSV_RAW.BRONZE TO ROLE loading_role;
GRANT CREATE STAGE, USAGE ON SCHEMA HEALTHCARE_CSV_RAW.BRONZE TO ROLE transform_role;
GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA HEALTHCARE_CSV_RAW.bronze TO ROLE loading_role;
