USE ROLE transform_role;
USE WAREHOUSE TRANSFORMING;
USE DATABASE HEALTHCARE_CSV_RAW;
USE SCHEMA HEALTHCARE_CSV_RAW.BRONZE;

-- 3. CREATION OF DATABASES FOR SYNTHEA
CREATE DATABASE IF NOT EXISTS HEALTHCARE_CSV_RAW;
CREATE DATABASE IF NOT EXISTS HEALTHCARE_ANALYTICS_NEW;
CREATE DATABASE IF NOT EXISTS "_RAW";


-- 4. CREATE SCHEMA IN THE DATABASES
CREATE SCHEMA HEALTHCARE_CSV_RAW.bronze;
CREATE SCHEMA HEALTHCARE_ANALYTICS_NEW.SILVER;
CREATE SCHEMA HEALTHCARE_ANALYTICS_NEW.GOLD;
CREATE SCHEMA IF NOT EXISTS "_RAW".PUBLIC;


