{{ config(materialized='table') }}

WITH silver_data as (
select
claimn_id
, patient_id
, "PROVIDERID"
, "PRIMARYPATIENTINSURANCEID"
, "SECONDARYPATIENTINSURANCEID"
, "DEPARTMENTID"
, "PATIENTDEPARTMENTID"
, "DIAGNOSIS1"
, "DIAGNOSIS2"
, "DIAGNOSIS3"
, "DIAGNOSIS4"
, "DIAGNOSIS5"
, "DIAGNOSIS6"
, "DIAGNOSIS7"
, "DIAGNOSIS8"
, "REFERRINGPROVIDERID"
, "APPOINTMENTID"
, "CURRENTILLNESSDATE"
, "SERVICEDATE"
, "SUPERVISINGPROVIDERID"
, "STATUS1"
, "STATUS2"
, "STATUSP"
, "OUTSTANDING1"
, "OUTSTANDING2"
, "OUTSTANDINGP"
, "LASTBILLEDDATE1"
, "LASTBILLEDDATE2"
, "LASTBILLEDDATEP"
, "HEALTHCARECLAIMTYPEID1"
, "HEALTHCARECLAIMTYPEID2"
from {{ ref('csv_silver__claims') }}
)

select * from silver_data

