{{ config(
    materialized='table',
    database='HEALTHCARE_ANALYTICS',
    schema='SILVER'
) }}


select
"OBSERVATION_DT" AS OBSERVATION_DATE
, "PATIENT" AS PATIENT_ID
, "ENCOUNTER" AS ENCOUTER_ID
, "CATEGORY" AS OBSERVATION_CATEGORY
, "CODE" AS OBSERVATION_CODE
, "DESCRIPTION" AS OBSERVATION_DESCRIPTION
, "VALUE" AS OBSERVATION_VALUE
, "UNITS" AS OBSERVATION_UNITS
, "TYPE" AS OBSERVATION_TYPE
from {{ ref('stg_clinical_data__json_observations') }}
