-- Drop & recreate (clean slate)
DROP DATABASE IF EXISTS HCB;
DROP DATABASE IF EXISTS HJB;
DROP DATABASE IF EXISTS HDB;
DROP DATABASE IF EXISTS HEALTHCARE_ANALYTICS_NEW;

CREATE DATABASE HCB;
CREATE SCHEMA HCB.BRONZE;

CREATE DATABASE HJB;
CREATE SCHEMA HJB.STAGING;
CREATE SCHEMA HJB.BRONZE;

CREATE DATABASE HDB;
CREATE SCHEMA HDB.STAGING;
CREATE SCHEMA HDB.BRONZE;

CREATE DATABASE HEALTHCARE_ANALYTICS_NEW;