-- Standardize vars here (or pass from Python -D)
SET HCB_DB = 'HCB';
SET HJB_DB = 'HJB';
SET HCB_SCHEMA = 'BRONZE';
SET HJB_STAGING_SCHEMA = 'STAGING';
SET HJB_BRONZE_SCHEMA = 'BRONZE';

-- Create CSV DB/Schema
CREATE DATABASE IDENTIFIER($HCB_DB);
CREATE SCHEMA IDENTIFIER($HCB_DB).($HCB_SCHEMA);

-- Create JSON DB/Schemas
CREATE DATABASE IDENTIFIER($HJB_DB);
CREATE SCHEMA IDENTIFIER($HJB_DB).IDENTIFIER($HJB_STAGING_SCHEMA);
CREATE SCHEMA IDENTIFIER($HJB_DB).IDENTIFIER($HJB_BRONZE_SCHEMA);
