-- Drop & recreate (clean slate)
DROP DATABASE IF EXISTS HCB;
DROP DATABASE IF EXISTS HJB;
DROP DATABASE IF EXISTS HDB;
DROP DATABASE IF EXISTS HEALTHCARE_ANALYTICS_NEW;

CREATE DATABASE HCB;
CREATE SCHEMA HCB.LOADING;
CREATE SCHEMA HCB.STAGING;

CREATE DATABASE HJB;
CREATE SCHEMA HJB.STAGING;
CREATE SCHEMA HJB.LOADING;

CREATE DATABASE HDB;
CREATE SCHEMA HDB.STAGING;
CREATE SCHEMA HDB.LOADING;

CREATE DATABASE HEALTHCARE_ANALYTICS_NEW;