-- 01_setup_healthcare_env.sql

-- create a tiny dev warehouse
CREATE WAREHOUSE IF NOT EXISTS TRANSFORMING WITH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- (optional) create TRANSFORM role if you don’t have it

CREATE ROLE IF NOT EXISTS TRANSFORM;
GRANT USAGE ON WAREHOUSE TRANSFORMING TO ROLE TRANSFORM;

-- Create the user HEALTHCARE
CREATE USER HEALTHCARE
  PASSWORD = 'Healthcare_User123'
  DEFAULT_ROLE = TRANSFORM
  DEFAULT_WAREHOUSE = TRANSFORMING
  MUST_CHANGE_PASSWORD = FALSE
  COMMENT = 'User for Healthcare project transformations';
  

CREATE OR REPLACE DATABASE HEALTHCARE_RAW;
CREATE OR REPLACE DATABASE HEALTHCARE_ANALYTICS;

-- grants
GRANT OWNERSHIP ON DATABASE HEALTHCARE_RAW TO ROLE TRANSFORM COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE HEALTHCARE_ANALYTICS TO ROLE TRANSFORM COPY CURRENT GRANTS;
GRANT USAGE ON DATABASE HEALTHCARE_RAW TO ROLE TRANSFORM;
GRANT USAGE ON DATABASE HEALTHCARE_ANALYTICS TO ROLE TRANSFORM;


-- switch to transform role for subsequent steps
USE ROLE TRANSFORM;
USE WAREHOUSE TRANSFORMING;

-- schemas
USE DATABASE HEALTHCARE_RAW;
CREATE OR REPLACE SCHEMA RAW_DATA;
CREATE OR REPLACE SCHEMA EXTERNAL_STAGES;
CREATE OR REPLACE SCHEMA UTIL;

-- target db for dbt models (optional)
USE DATABASE HEALTHCARE_ANALYTICS;
CREATE OR REPLACE SCHEMA DEV;