
CREATE OR REPLACE TASK LOADING.MASTER_TO_L1_MERGE 
    
    AS  CALL LOADING.MASTER_TO_L1_MERGE(select max(batch_no)  from LOADING.MASTER_JSON);

CREATE OR REPLACE TASK LOADING.L1_TO_L2_MERGE AFTER MASTER_TO_L1_MERGE 
    
    AS CALL LOADING.L1_TO_L2_MERGE(select max(batch_no)  from LOADING.MASTER_JSON);

CREATE OR REPLACE  TASK LOADING.SP_APPLY_SCHEMA_CHANGES AFTER L1_TO_L2_MERGE 
    
    AS CALL LOADING.SP_APPLY_SCHEMA_CHANGES(select max(batch_no)  from LOADING.MASTER_JSON);

CREATE  OR REPLACE TASK LOADING.SP_LOAD_SILVER_DATA AFTER SP_APPLY_SCHEMA_CHANGES
    
    AS CALL LOADING.SP_LOAD_SILVER_DATA(select max(batch_no)  from LOADING.MASTER_JSON);

CREATE  OR REPLACE TASK LOADING.SP_PIPELINE_AUDIT AFTER SP_LOAD_SILVER_DATA
    
    AS CALL LOADING.SP_PIPELINE_AUDIT(select max(batch_no)  from LOADING.MASTER_JSON);


ALTER TASK MASTER_TO_L1_MERGE SUSPEND;
ALTER TASK L1_TO_L2_MERGE SUSPEND;  
ALTER TASK SP_APPLY_SCHEMA_CHANGES SUSPEND; 
ALTER TASK SP_LOAD_SILVER_DATA SUSPEND;
ALTER TASK SP_PIPELINE_AUDIT SUSPEND;


ALTER TASK MASTER_TO_L1_MERGE 
  SET SCHEDULE = 'USING CRON 0 0 1 * * Asia/Kolkata';  -- 1st day, 12AM IST every month

 
ALTER TASK SP_PIPELINE_AUDIT RESUME;
ALTER TASK SP_LOAD_SILVER_DATA RESUME;
ALTER TASK SP_APPLY_SCHEMA_CHANGES RESUME; 
ALTER TASK L1_TO_L2_MERGE RESUME; 
ALTER TASK MASTER_TO_L1_MERGE RESUME;

select count(*), count(distinct patient_id) from synthea_flattened_l1;