EXECUTE TASK MASTER_TO_L1_MERGE;


select * from 
(SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(RESULT_LIMIT => 100)) 
ORDER BY SCHEDULED_TIME DESC)  where database_name  = 'HEALTHCARE_JSON_RAW';
