USE ROLE transform_role;
USE WAREHOUSE TRANSFORMING;

-- 3. CREATION OF DATABASES FOR SYNTHEA
CREATE DATABASE IF NOT EXISTS HDB;


-- 4. CREATE SCHEMA IN THE DATABASES
CREATE SCHEMA HDB.STAGING;
CREATE SCHEMA HDB.BRONZE;
