sources:
  - name: csv_data
    database: HCB
    schema: BRONZE
    tables:
      - name: allergies
      - name: careplans
      - name: claims
      - name: claims_transactions
      - name: conditions
      - name: devices
      - name: encounters
      - name: imaging_studies
      - name: immunizations
      - name: medications
      - name: observations
      - name: organizations
      - name: patients
      - name: payer_transitions
      - name: payers
      - name: procedures
      - name: providers
      - name: supplies
      - name: table_column_preview
      - name: bronze
  - name: json_data
    database: HJB
    schema: BRONZE
    tables:
      - name: AllergyIntolerance
      - name: CarePlan
      - name: Claim
      - name: Condition
      - name: DiagnosticReport
      - name: Encounter
      - name: ExplanationOfBenefit
      - name: Goal
      - name: ImagingStudy
      - name: Immunization
      - name: MedicationRequest
      - name: Observation
      - name: Organization
      - name: Patient
      - name: Practitioner
      - name: Procedure
